import 'dotenv/config';
import express from 'express'; import helmet from 'helmet'; import morgan from 'morgan'; import crypto from 'crypto'; import PDFDocument from 'pdfkit';
import {createClient} from '@supabase/supabase-js';
const app=express(); const port=process.env.PORT||3000;
const supabase= createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
app.use(helmet({contentSecurityPolicy:false})); app.use(morgan('tiny')); app.use(express.json({limit:'1mb'})); app.use(express.static('public'));
const courses={GE:350000,FC:550000,CC:500000,PACK:990000};
app.get('/api/config',(req,res)=>res.json({wompiPublicKey:process.env.WOMPI_PUBLIC_KEY||'',appUrl:process.env.APP_URL||'',whatsapp:process.env.WHATSAPP_NUMBER||''}));
app.post('/api/payment/create',async(req,res)=>{try{const {userId,courseId,email}=req.body;if(!userId||!courseId||!email||!courses[courseId])return res.status(400).json({error:'Datos incompletos'}); const {data:enrollment,error:e}=await supabase.from('enrollments').upsert({user_id:userId,course_id:courseId,status:'pending'},{onConflict:'user_id,course_id'}).select().single(); if(e)throw e; const reference='GS-'+crypto.randomUUID().replaceAll('-','').slice(0,24); const amount=courses[courseId]; const secret=process.env.WOMPI_INTEGRITY_SECRET; if(!secret) return res.status(500).json({error:'Falta WOMPI_INTEGRITY_SECRET'}); const integrity=crypto.createHash('sha256').update(reference+String(amount*100)+'COP'+secret).digest('hex'); await supabase.from('payments').insert({enrollment_id:enrollment.id,reference,amount_cop:amount,status:'PENDING'}); res.json({reference,amountInCents:amount*100,currency:'COP',integrity,publicKey:process.env.WOMPI_PUBLIC_KEY,redirectUrl:(process.env.APP_URL||'')+'/pago.html'});}catch(e){res.status(500).json({error:e.message})}});
function getPath(obj,path){return path.split('.').reduce((a,k)=>a?.[k],obj)}
function validEvent(body){const secret=process.env.WOMPI_EVENTS_SECRET;if(!secret)return false;const s=body.signature||{};const raw=(s.properties||[]).map(p=>String(getPath(body.data,p)||'')).join('')+String(s.timestamp||'')+secret;const expected=crypto.createHash('sha256').update(raw).digest('hex');return expected===(s.checksum||'')||expected===(body?.signature?.checksum||'');}
app.post('/api/wompi/webhook',async(req,res)=>{try{if(!validEvent(req.body))return res.status(401).send('invalid signature'); const event=req.body; if(event.event==='transaction.updated'){const t=event.data?.transaction; const status=t?.status||'PENDING'; const {data:p}=await supabase.from('payments').update({wompi_transaction_id:t?.id,status,raw_event:event,updated_at:new Date().toISOString()}).eq('reference',t?.reference).select('enrollment_id').single(); if(p?.enrollment_id&&status==='APPROVED') await supabase.from('enrollments').update({status:'paid'}).eq('id',p.enrollment_id);}res.json({received:true});}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/stats',async(req,res)=>{const [{count:students},{count:paid},{count:pending}]=await Promise.all([supabase.from('profiles').select('*',{count:'exact',head:true}).eq('role','student'),supabase.from('enrollments').select('*',{count:'exact',head:true}).in('status',['paid','active','completed']),supabase.from('enrollments').select('*',{count:'exact',head:true}).eq('status','pending')]);res.json({students:students||0,paid:paid||0,pending:pending||0})});
app.get('/api/admin/students',async(req,res)=>{const {data,error}=await supabase.from('profiles').select('id,full_name,document,phone,city,created_at,enrollments(id,course_id,status,progress,created_at)').eq('role','student').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json(data)});
app.post('/api/admin/enrollment/:id/status',async(req,res)=>{const {status}=req.body;const allowed=['pending','paid','active','completed','cancelled'];if(!allowed.includes(status))return res.status(400).json({error:'Estado inválido'});const {data,error}=await supabase.from('enrollments').update({status}).eq('id',req.params.id).select().single();if(error)return res.status(500).json({error:error.message});if(status==='completed')await issueCertificate(data.id);res.json(data)});
async function issueCertificate(enrollmentId){const {data:e}=await supabase.from('enrollments').select('id,user_id,course_id,profiles(full_name),courses(title,hours)').eq('id',enrollmentId).single();if(!e)return;const num='GS-'+new Date().getFullYear()+'-'+crypto.randomBytes(4).toString('hex').toUpperCase();return supabase.from('certificates').upsert({enrollment_id:enrollmentId,certificate_number:num},{onConflict:'enrollment_id'}).select().single()}
app.get('/api/certificate/:id.pdf',async(req,res)=>{const {data:c,error}=await supabase.from('certificates').select('certificate_number,issued_at,enrollment_id,enrollments(profiles(full_name),courses(title,hours))').eq('id',req.params.id).single();if(error||!c)return res.status(404).send('No encontrado');res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`inline; filename=${c.certificate_number}.pdf`);const d=new PDFDocument({size:'A4',margin:60});d.pipe(res);d.fontSize(14).text('GRUPO SANTO',{align:'center'});d.moveDown(2);d.fontSize(30).text('CERTIFICADO',{align:'center'});d.moveDown();d.fontSize(16).text('Se certifica que',{align:'center'});d.moveDown(.5);d.fontSize(24).text(c.enrollments.profiles.full_name,{align:'center'});d.moveDown();d.fontSize(15).text('ha completado satisfactoriamente el programa',{align:'center'});d.moveDown(.5);d.fontSize(20).text(c.enrollments.courses.title,{align:'center'});d.moveDown();d.fontSize(13).text(`${c.enrollments.courses.hours} horas · Certificado ${c.certificate_number}`,{align:'center'});d.moveDown(4);d.text(new Date(c.issued_at).toLocaleDateString('es-CO'),{align:'center'});d.end()});
app.get('*',(req,res)=>res.sendFile(process.cwd()+'/public/index.html'));app.listen(port,()=>console.log(`Grupo Santo 3.0: http://localhost:${port}`));
